# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/torske_site',
                'doc_host': 'https://jimgaas.github.io',
                'git_url': 'https://github.com/jimgaas/torske_site',
                'lib_path': 'torske_site'},
  'syms': {'torske_site.db': {'torske_site.db.get_db': ('db.html#get_db', 'torske_site/db.py')}, 'torske_site.db_dc': {}}}
