"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_db.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'get']

# %% ../nbs/00_db.ipynb #3fc18806
from fasthtml.common import *

# %% ../nbs/00_db.ipynb #c31cab7a
app, rt = fast_app()

@rt('/')
def get(): return Titled("Hello World", P("Hello, world!"))


