"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_db.ipynb.

# %% auto #0
__all__ = ['testing', 'root_dir', 'db', 'get_db']

# %% ../nbs/00_db.ipynb #b6e6b961
from fastcore.utils import *
from fastlite import *
from pathlib import Path
from fastmigrate import create_db, run_migrations, setup_logging
from tempfile import NamedTemporaryFile
import mistletoe

# %% ../nbs/00_db.ipynb #d6deb12f
testing = False
root_dir = Path().home() / 'torske_site'

# %% ../nbs/00_db.ipynb #99d96a24
def get_db():
    "Create a new or read in existing database tables for solveit app"
    if testing:
        db_path = NamedTemporaryFile(suffix=".db").name  # Can't use :memory: b/c fastmigrate does not support it (yet)
    else:
        db_path = '/app/data/torskeklubben/data.db'
    
    create_db(db_path)
    run_migrations(db_path, root_dir/'migrations/')
    
    db = database(db_path)
    return db
     

# %% ../nbs/00_db.ipynb #f85ba8e2
db = get_db()

# %% ../nbs/00_db.ipynb #fead96d7
from .db_dc import *
from . import db_dc
db.link_dcs(db_dc)
