"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_db.ipynb.

# %% auto #0
__all__ = ['testing']

# %% ../nbs/00_db.ipynb #b6e6b961
from fastcore.utils import *
from fastlite import *

# %% ../nbs/00_db.ipynb #d6deb12f
testing = False

# %% ../nbs/00_db.ipynb #f85ba8e2
if testing:
    db = database(":memory:")
else:
    db_path = os.path.expanduser('/app/data/torskeklubben/data.db')
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    db = database(db_path)
